import os
import glob

replacements = {
    'Ingeniera': 'Ingeniería',
    'ingeniera': 'ingeniería',
    'ms': 'más',
    'estndares': 'estándares',
    'energtica': 'energética',
    'Energa': 'Energía',
    'elctrica': 'eléctrica',
    'Elctrica': 'Eléctrica',
    'elctricos': 'eléctricos',
    'elctrico': 'eléctrico',
    'mecnica': 'mecánica',
    'Mecnica': 'Mecánica',
    'mecnicos': 'mecánicos',
    'electrnica': 'electrónica',
    'Electrnica': 'Electrónica',
    'automatizacin': 'automatización',
    'sensorizacin': 'sensorización',
    'comunicacin': 'comunicación',
    'cmaras': 'cámaras',
    'cǭmaras': 'cámaras',
    'gestin': 'gestión',
    'energas': 'energías',
    'tensin': 'tensión',
    'integracin': 'integración',
    'Integracin': 'Integración',
    'mltiples': 'múltiples',
    'mǧltiples': 'múltiples',
    'Quines': 'Quiénes',
    'compaa': 'compañía',
    'reas': 'áreas',
    'regin': 'región',
    'Misin': 'Misión',
    'Visin': 'Visión',
    'lderes': 'líderes',
    'garanta': 'garantía',
    'xito': 'éxito',
    'tecnolgico': 'tecnológico',
    'tecnologa': 'tecnología',
    'tecnologas': 'tecnologías',
    'diseo': 'diseño',
    'Diseo': 'Diseño',
    'Anlisis': 'Análisis',
    'Anǭlisis': 'Análisis',
    'Hidrulicos': 'Hidráulicos',
    'Hidrǭulicos': 'Hidráulicos',
    'Neumticos': 'Neumáticos',
    'Neumǭticos': 'Neumáticos',
    'tcnico': 'técnico',
    'tǸcnico': 'técnico',
    'elǸctrico': 'eléctrico',
    'elǸctrica': 'eléctrica',
    'electrnico': 'electrónico',
    'mecǭnico': 'mecánico',
    'Mecǭnica': 'Mecánica',
    'Mecǭnicos': 'Mecánicos',
    'mecǭnicos': 'mecánicos',
    'combustin': 'combustión',
    'grǧas': 'grúas',
    'logstica': 'logística',
    'ejecucin': 'ejecución',
    'construccin': 'construcción',
    'instalacin': 'instalación',
    'informacin': 'información',
    'da': 'día',
    'proteccin': 'protección',
    'optimizacin': 'optimización',
    'conservacin': 'conservación',
    'implementacin': 'implementación',
    'Mantenimiento de PLCs': 'Mantenimiento de PLC',
    'estǭndares': 'estándares',
    'Mecǭnica': 'Mecánica',
    'Mecǭnicos': 'Mecánicos',
    'mecǭnicos': 'mecánicos',
    'tǸcnico': 'técnico',
    'elǸctrico': 'eléctrico',
    'elǸctrica': 'eléctrica',
    'hidrǭulicos': 'hidráulicos',
    'neumǭticos': 'neumáticos',
    'ǭ': 'á',
    'Ǹ': 'é',
    '': 'í',
    '': 'ó',
    'ǧ': 'ú',
    '': 'ñ',
    '': 'Ñ',
    '': 'í',
    '': 'ó',
}

for filepath in glob.glob('src/**/*.tsx', recursive=True):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    
    # Do replacements
    for old, new in replacements.items():
        content = content.replace(old, new)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

print("Replaced all encoding errors.")
